title: Gowtham
email: blog@gowtham.dev
description: >-
  rants, learnings and documentations from a 1x engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gowtham.dev"
permalink: /:categories/:slug:output_ext
links:
  github: https://github.com/gowthamgts
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
    values:
      seo_description_max_words: 200
  - scope:
      path: ""
      type: "posts"
    values:
      category: blog

author:
  name: Gowtham Gopalakrishnan
  url: https://gowtham.dev

header_pages:
  - blog.md
  - til.md

social:
  name: Gowtham Gopalakrishnan

exclude:
  - README.md
  - .github/
